services:
  amp:
    image: ghcr.io/kingofls9909/amp-docker:latest
    container_name: amp-docker
    restart: unless-stopped
    mac_address: "02:42:ac:11:00:02"
    environment:
      - AMP_LICENCE=${AMP_LICENCE}
      - AMP_USERNAME=${AMP_USERNAME}
      - AMP_PASSWORD=${AMP_PASSWORD}
      - AMP_PORT=${AMP_PORT:-8080}
    volumes:
      - ./ampdata:/home/amp/
    ports:
      - "${HOST_PORT:-8180}:${AMP_PORT:-8080}"  # Web UI 
      - "${SFTP_PORT:-2224}:2223"               # AMP SFTP Management